default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: heylaundry_development 

test:
  <<: *default
  database: heylaundry_test 

production:
  <<: *default
  database: heylaundry_production
